### ISSUE TITLE
Validator doesn't resolve refs for a whole response

### ISSUE THREAD

**Issue by IvanStawski** [RuntimeTools/chai-openapi-response-validator#18] opened 2019-10-09 09:18 UTC
**Steps to reproduce:**

1. Take an OAS3 file like:
```openapi: 3.0.0
info:
  title: example
  version: "0.1"
  description: test
servers:
  - url: /api
    description: local
paths:
  /feature:
    post:
      description: Create new feature in a system
      responses:
        "400":
          $ref: '#/components/responses/InvalidRequest'
components:
  responses:
    InvalidRequest:
      description: Request was rejected by server due to invalid request parameters or something
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
```

2. Use it as the specification for a test
3. Let the test check POST /api/feature with response "404"

Actual result: 
```
AssertionError: expected response to satisfy API spec:
{ message: 'The response was not valid.',
  errors:
   [ { errorCode: 'type.openapi.responseValidation',
       message: 'response should be null' } ],
  actualResponse: { status: 400, body: { error: [Object] } } }```

**Comment by rwalle61** [comment] 2019-10-18 08:52
@JonnySpruce I thought we didn't handle `servers` like this? (and https://github.com/RuntimeTools/chai-openapi-response-validator/pull/19 will add that support). 

In any case, @IvanStawski we shall recreate and investigate

**Comment by IvanStawski** [comment] 2019-10-25 11:18
@rwalle61 I'm think that the problem not in `servers` like this. I suppose that the issue 
`responses:
        "400":
          $ref: '#/components/responses/InvalidRequest'`

**Comment by IvanStawski** [comment] 2019-10-29 11:20
Maybe we should update library `openapi-response-validator` to the latest version?

**Comment by rwalle61** [comment] 2019-11-08 08:50
@IvanStawski I just realised - what is in `'#/components/responses/InvalidRequest'`? If you have not specified any content in `InvalidRequest`, then (I believe) you are effectively specifying that the `400` response should have no body (`null`). This package would then be *correctly* saying that `response should be null` but is in fact some object.

I have personally been caught out by this before. If you don't want to care whether the `400` response has a body or not, then I suggest just using `expect(res.status).to.equal(400)` and not adding `expect(res).to.satisfyApiSpec`.

I'm open to a better way for this package to handle these cases, so feel free to suggest one!

**Comment by rwalle61** [comment] 2019-11-08 08:53
If that's really the cause, then and you agree this is expected behaviour (not a bug) then please close the issue.

Alternatively, suggest an enhancement for us to discuss and pick up :)

**Comment by kgehmlich** [comment] 2019-11-12 17:26
@rwalle61 I just ran into the same problem. Pasting my OAS 3 and JS test files here (some names have been changed for security reasons):

**OpenAPI:**
```
openapi: 3.0.0
info:
  title: Static API
  description: Provides access to [REDACTED].
  version: '0.1'

servers:
  - url: /api/v1

security:
  - BearerAuth:
      - read
      - write

paths:
  /things:
    get:
      summary: Returns a list of things
      description: ''
      tags:
        - Inventory
      responses:
        '200':
          description: A JSON object containing a list of things
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    $ref: '#/components/schemas/ThingList'
        '401':
          $ref: '#/components/responses/Unauthorized'


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Error:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string

    Thing:
      type: object
      properties:
        name:
          type: string
      required:
        - name

    ThingList:
      type: array
      items:
        $ref: '#/components/schemas/Thing'

  responses:
    Unauthorized:
      description: Unauthorized

tags:
  - name: Inventory
    description: Fetch inventory information
```

**test-api.js**
```
const resolve = require('path').resolve
const axios = require('axios').default

// Set up Chai
const chai = require('chai')
const expect = chai.expect

// Import this plugin
const chaiResponseValidator = require('chai-openapi-response-validator')

// Settings
const baseUrl = 'https://[REDACTED].net/api/v1'
const bearerToken = '[REDACTED]]'
const authorizedConfig = {
  headers: { Authorization: 'bearer ' + bearerToken }
}
const unauthorizedConfig = {
  // axios throws an error for non 2xx response codes, but we want to treat 4xx as expected
  validateStatus: null
}

// Load an OpenAPI file (YAML or JSON) into this plugin
chai.use(chaiResponseValidator(resolve('swagger.yaml')))

// Write your test (e.g. using Mocha)
describe('GET /things', function () {
  const testUrl = baseUrl + '/things'

  it('should satisfy OpenAPI spec when authorized', async function () {
    const reponse = await axios.get(testUrl, authorizedConfig)
    expect(reponse.status).to.equal(200)
    expect(reponse).to.satisfyApiSpec
  })

  it('should satisfy OpenAPI spec when not authorized', async function () {
    const response = await axios.get(testUrl, unauthorizedConfig)
    expect(response.status).to.equal(401)
    expect(response).to.satisfyApiSpec
  })
})
```

**Comment by kgehmlich** [comment] 2019-11-12 17:33
I just tried in-lining the `$ref` and that didn't help. I had to make the `401` response look like the following for the validation to pass:
```
'401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
```

Note that adding these fields to the `$ref`ed response generates the error mentioned above.

**Comment by rwalle61** [comment] 2019-11-17 20:34
Thanks @kgehmlich, I will recreate and investigate whether the fix needs to be made in our package or openapi-response-validator

**Comment by rwalle61** [comment] 2019-11-21 19:56
Fyi on my local branch, a change in our package seems to fix this problem, at least for OpenAPI 3 files.  I'll PR it as soon as it's properly ready.

**Explanation**

Currently [we're passing `openapi-response-validator` an `expectedResponse`](https://github.com/RuntimeTools/chai-openapi-response-validator/blob/master/lib/index.js#L107). (which is an object e.g. `{ '$ref': '#/components/responses/Foo' }`)

I expected `openapi-response-validator` to be able to find this `$ref`, because we pass it our OpenAPI 3 `components` object. In general, OpenAPI 3 specs should define `$ref`'d response schemas in their `components/responses` section.

However, in general OpenAPI 2 specs should define response schemas in the `responses` section. Perhaps that's why `openapi-response-validator` seems to expect all responses to be supplied in the `responses` field. (The project originally supported only OpenAPI 2)

So making `expectedResponse` the `$ref`'d response object itself (rather than `{ '$ref': '#/components/responses/Foo' }` seems to fixes the problem.

**Comment by rwalle61** [comment] 2019-11-21 20:45
@IvanStawski @kgehmlich would you like to review before or after I publish?

**Closed** 2019-11-30 19:01 UTC

**Comment by rwalle61** [comment] 2019-12-01 11:19
I've just published the fix in `0.4.0` - please verify, and reopen if needed :)

**Comment by IvanStawski** [comment] 2019-12-02 09:32
@rwalle61 Thank you. Seems working fine for me.

**Comment by kgehmlich** [comment] 2020-03-11 14:33
Finally got around to testing this again, works well with the new changes. Thanks @rwalle61 !
